apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  annotations:
    architecture: x86_64
    authoritative-source-url: registry.access.redhat.com
    build-date: 2020-01-30T08:17:04.175507
    commit.image.appsody.dev/author: Oliver Rodriguez <oliverd.rodriguez@gmail.com>
    commit.image.appsody.dev/committer: GitHub <noreply@github.com>
    commit.image.appsody.dev/date: Tue Apr 21 16:09:44 2020 -0500
    commit.image.appsody.dev/message: Update home.html
    commit.stack.appsody.dev/author: kilnerm <38245247+kilnerm@users.noreply.github.com>
    commit.stack.appsody.dev/committer: GitHub <noreply@github.com>
    commit.stack.appsody.dev/contextDir: /incubator/nodejs
    commit.stack.appsody.dev/date: Fri Apr 3 09:22:57 2020 +0100
    commit.stack.appsody.dev/message: 'Merge pull request #316 from groeges/release-0.6'
    description: This image contains the Kabanero development stack for the Nodejs
      collection
    distribution-scope: public
    help: For more information visit https://github.com/sclorg/s2i-nodejs-container
    image.opencontainers.org/created: "2020-04-21T23:45:33-05:00"
    image.opencontainers.org/documentation: https://github.com/odrodrig/refarch-cloudnative-bluecompute-web-appsody
    image.opencontainers.org/revision: f8da5a1f073e5daf58675d51f7d599121eea9eb6-modified
    image.opencontainers.org/source: https://github.com/odrodrig/refarch-cloudnative-bluecompute-web-appsody/tree/master
    image.opencontainers.org/url: https://github.com/odrodrig/refarch-cloudnative-bluecompute-web-appsody
    k8s.io/description: Node.js 12 available as container is a base platform for building
      and running various Node.js 12 applications and frameworks. Node.js is a platform
      built on Chrome's JavaScript runtime for easily building fast, scalable network
      applications. Node.js uses an event-driven, non-blocking I/O model that makes
      it lightweight and efficient, perfect for data-intensive real-time applications
      that run across distributed devices.
    k8s.io/display-name: Node.js 12
    maintainer: SoftwareCollections.org <sclorg@redhat.com>
    name: oliver-custom/custom-node
    openshift.io/expose-services: 8080:http
    openshift.io/tags: builder,nodejs,nodejs12
    redhat.com/build-host: cpt-1001.osbs.prod.upshift.rdu2.redhat.com
    redhat.com/component: nodejs-12-container
    redhat.com/deployments-dir: /opt/app-root/src
    redhat.com/dev-mode: DEV_MODE:false
    redhat.com/dev-mode.port: DEBUG_PORT:5858
    redhat.com/license_terms: https://www.redhat.com/en/about/red-hat-end-user-license-agreements#UBI
    release: "27"
    s2i.io/scripts-url: image:///usr/libexec/s2i
    s2i.openshift.io/scripts-url: image:///usr/libexec/s2i
    stack.appsody.dev/authors: Sam Roberts <vieuxtech@gmail.com>
    stack.appsody.dev/configured: dev.local/appsody/custom-node:0.4
    stack.appsody.dev/created: "2020-04-20T00:55:38-05:00"
    stack.appsody.dev/description: Runtime for Node.js applications
    stack.appsody.dev/documentation: https://github.com/kabanero-io/collections/tree/master/incubator/nodejs/README.md
    stack.appsody.dev/licenses: Apache-2.0
    stack.appsody.dev/revision: 27a3254c80e6c5367a76e6099c2e18b393d15841
    stack.appsody.dev/source: https://github.com/kabanero-io/collections/tree/master/incubator/nodejs/image
    stack.appsody.dev/tag: dev.local/appsody/custom-node:0.4.0
    stack.appsody.dev/title: Custom Node
    stack.appsody.dev/url: https://github.com/kabanero-io/collections/tree/master/incubator/nodejs
    summary: Image for Kabanero Nodejs development
    url: https://access.redhat.com/containers/#/registry.access.redhat.com/ubi8/nodejs-12/images/1-27
    usage: s2i build <SOURCE-REPOSITORY> ubi8/nodejs-12:latest <APP-NAME>
    vcs-ref: 9a85b86edcc6c765692f15311abe259b0f9997b2
    vcs-type: git
    vendor: Kabanero
    version: 0.0.1
  creationTimestamp: null
  labels:
    image.opencontainers.org/title: playbacktest
    stack.appsody.dev/id: custom-node
    stack.appsody.dev/version: 0.4.0
  name: web
spec:
  applicationImage: dev.local/playbacktest
  createKnativeService: false
  expose: true
  pullSecret: ibm-cr-pull-secret
  service:
    port: 80
    targetPort: 8000
    type: ClusterIP
  stack: nodejs
  version: 0.6.0
